### ISSUE TITLE
[Bug] Explore Bar issue

### ISSUE THREAD

**Issue by kraytaps** [onlinkers/event-discovery-prototype#42]
**Describe the bug**
Explore bar looks wrong, search bar is too far down

**To Reproduce**
1. Go to the Discover page

**Expected behavior**
Middle explore button should be larger
Also want to add a 'shadow' above the explore bar to make it visible that its separate from the rest of the screen. White on white causes what can be seen below
<img width="398" alt="Screen Shot 2020-03-10 at 12 22 14 AM" src="https://user-images.githubusercontent.com/44561376/76288988-57a6f580-6265-11ea-9c31-229727b33e2e.png">

**Screenshots**
![Screenshot (213)](https://user-images.githubusercontent.com/46850879/75808349-cd7a0100-5d3b-11ea-863d-96b4fbbf6be7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chromium Edge

**Comment by kraytaps** [comment]
@ad2969 do u wanna take this one?

#### Notes
* I was wondering if we really need to make the "Eclipse" a vue file and if we can't just keep it as an svg for consistency, which leads me to my next point
* What are the benefits of making it a vue file - e.g. can we include multiple SVGs and individually control their opacities/color or smth because that would be sick

**Comment by kraytaps** [comment]
Also can confirm it looks the same way on my 125% resolution scale

**Comment by cadrianxyz** [comment]
> @ad2969 do u wanna take this one?
> 
> #### Notes
> * I was wondering if we really need to make the "Eclipse" a vue file and if we can't just keep it as an svg for consistency, which leads me to my next point
> * What are the benefits of making it a vue file - e.g. can we include multiple SVGs and individually control their opacities/color or smth because that would be sick

Not particularly. I'd suggest we both stick to tasks for this week - I'm backlogging this and I think its a relatively easy first issue that any onboard-ers can take up, or if either of us finish assigned tasks early. Will re-look at this during Sunday meeting.

As for questions, google is the answer but I think I remember that Vue doesn't offer importing svg files natively, there's probs an external package that does this (might want to consider if we are using a ton of svg files in the future, but again I didn't really look it up). Otherwise, I assume wrapping svgs into vue files gives a bit more control as you can `v:model` the svg's props? Don't remember if I tried but might be worth taking a stab at

**Comment by kraytaps** [comment]
Sure. We actually do have a lot of svgs though. I guess for the ones we wanna dynamically style we can do that.

**Comment by cadrianxyz** [comment]
Starting an issue if you think we should - I think its pretty smart to, long run it would be such a hassle to wrap each svg into a `.vue` component
